---
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.x'
    - name: Test
      run: go test -race ./...
    - name: Test Reonce Build Tag
      run: go test -race -tags reonce ./...
    - name: Vet
      run: go vet ./...
